article/urls.py
# 引入path
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
# 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    path('article-detail/<int:id>/upload/jsons/group_data.json/', views.file_download, name='file_download'),
    path('article-detail/<int:id>/file_cluster', views.file_cluster, name='file_cluster'),
    path('article-detail/<int:id>/article/groups_result.json', views.show_result, name='show_result'),
    path('article-detail/<int:id>/sum', views.count, name='count'),
    path('article-data/', views.data_acquisition, name='data_acquisition'),

]

firstDjango/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


from django.contrib import admin
from django.urls import path,include
from blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', views.blog_index),
    path('blog/input_front', views.blog_input),
    path('article/', include('article.urls', namespace='article')),
    # include将路径分发给下一步处理；
    # namespace可以保证反查到唯一的url，即使不同的app使用了相同的url（后面会用到）
]

article/models.py
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone

# Create your models here.

# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者。参数 on_delete 用于指定数据删除的方式，避免两个关联表的数据不一致。
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()
    # 文章创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)
    # 文章更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    jsonfile = models.FileField(upload_to='jsons/',default=0)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

article/views.py
from django.shortcuts import render

# Create your views here.

# 导入数据模型ArticlePost
from .models import ArticlePost
import markdown
import os

# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
# 引入User模型
from django.contrib.auth.models import User


def article_list(request):
    # 取出所有博客文章
    articles = ArticlePost.objects.all()
    # 需要传递给模板（templates）的对象
    context = {'articles': articles}
    # render函数：载入模板，并返回context对象
    return render(request, 'article/list.html', context)


import markdown


# 文章详情
def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    # 将markdown语法渲染成html样式
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮扩展
                                         'markdown.extensions.codehilite',
                                     ])
    context = {'article': article}
    return render(request, 'article/detail.html', context)


# 写文章的视图
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            new_article.author = User.objects.get(id=1)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form}
        # 返回模板
        return render(request, 'article/create.html', context)


# 删文章
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = ArticlePost.objects.get(id=id)
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")


# 更新文章
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form}
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)


from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from matplotlib import pyplot as plt
from collections import defaultdict
from functools import reduce
import numpy as np
import json
import random


def file_download(request,id):
    # do something...
    with open('C:\\Users\Administrator.QH-20150404EHBO\PycharmProjects\\firstDjango\\upload\jsons\group_data.json',
              encoding='utf8') as f:
        c = f.readlines()
        return HttpResponse(json.dumps(c), content_type="application/json")





def sort_cluster(n_samples, centers, labels, n_cluster):
    '''
    sort cluster by center distances
    :param n_samples: list, samples
    :param centers: list, cluster center
    :param labels: list, cluster result
    :param n_cluster: int, cluster num
    :return: list, sorted cluster [[sample_idx,..],..]
    '''
    frequency = [0] * n_cluster
    for i in labels:
        frequency[i] += 1
    # label: frequency

    # select the biggest cluster
    max_label = 0
    max_frequency = 0
    for idx, i in enumerate(frequency):
        if i > max_frequency:
            max_label = idx
            max_frequency = i

    # sort cluster by distance
    cluster_sorted = [max_label]
    while len(cluster_sorted) < n_cluster:
        former_cluster = cluster_sorted[-1]
        idx = 0
        min_distance = 999
        for i in range(n_cluster):
            if i not in cluster_sorted:
                distance = np.linalg.norm(centers[former_cluster] - centers[i])
                if distance < min_distance:
                    min_distance = distance
                    idx = i
        cluster_sorted.append(idx)
    # sort elements in each cluster
    res = []
    for l_idx, label in enumerate(cluster_sorted):
        # if not first cluster, then compute distance with former cluster
        if label != max_label:
            l_idx -= 1
        cluster = []
        for idx, i in enumerate(labels):
            if i == label:
                cluster.append(idx)
        res.append(sorted(cluster, key=lambda x: np.linalg.norm(n_samples[x] - centers[cluster_sorted[l_idx]])))

    return res


def allocate(cluster_sorted, g):
    '''
    allocate cluster to different groups evenly
    :param cluster_sorted: list, cluster result
    :param g: int, group number
    :return: dict, groups
    '''
    cluster_sorted = reduce(lambda x, y: x + y, cluster_sorted)
    groups = defaultdict(list)
    i = 1
    while cluster_sorted:
        if i > g:
            i %= g
        groups[i].append(cluster_sorted.pop(0))
        i += 1
    return groups


def main():
    with open("C:\\Users\Administrator.QH-20150404EHBO\PycharmProjects\\firstDjango\\upload\jsons\group_data.json", encoding='utf8') as f:
        data = json.load(f)
    names = [k for k in data]
    max_k = 5  # max cluster num to test
    X = [data[k] for k in data]
    estimators = [(i, KMeans(n_clusters=i)) for i in range(2, max_k)]

    ss = []
    labels = []
    centers = []
    max_score = -2
    cluster_num = 0
    for k, est in estimators:
        est.fit(X)
        score = round(silhouette_score(X, est.labels_), 3)
        if score > max_score:
            labels = est.labels_
            max_score = score
            centers = est.cluster_centers_
            cluster_num = est.get_params()['n_clusters']
        ss.append(score)
        plt.text(k, score, score)
        # print(k, score)
        # print(est.get_params()['n_clusters'])

    # plot silhouette score for each k
    plt.xlim([1, 10])
    plt.xlabel('k')
    plt.ylabel('silhouette score')
    plt.plot(range(2, max_k), ss, 'o-', label=ss)
    plt.savefig('silhouette_score.png')

    # plot cluster result
    plt.cla()
    color_set = ['r', 'b', 'yellow', 'green', 'black', 'brown']
    brush = random.sample(color_set, cluster_num)
    c = [brush[l] for l in labels]
    plt.scatter(list(map(lambda x: x[2], X)), list(map(lambda x: x[3], X)),
                c=c,
                s=50,
                edgecolors='black')
    for idx, i in enumerate(X):
        plt.text(i[2], i[3], idx)
    plt.savefig('best_cluster_result.png')

    # allocate groups
    clusters_sorted = sort_cluster(X, centers, labels, cluster_num)
    # print(clusters)
    groups = allocate(clusters_sorted, 3)
    res2dict = {}
    for g in groups:
        res2dict[g] = [names[i] for i in groups[g]]
        # print([names[i] for i in groups[g]])
    return res2dict
    # with open('class_result.json', 'w', encoding='utf8') as f:
    #     json.dump(res2dict, f, ensure_ascii=False, indent=2)


def file_cluster(request,id):
    res2dict = main()
    return HttpResponse(json.dumps(res2dict), content_type="application/json")



def show_result(request,id):
    with open('C:\\Users\Administrator.QH-20150404EHBO\PycharmProjects\\firstDjango\\article\groups_result.json',encoding='utf-8') as f:
        d = f.readlines()
        return HttpResponse(json.dumps(d), content_type="application/json")



def count(request,id):
    resp = {'第一组': '油梦圆', '第二组': '申泳国', '第三组': '吴晓均'}
    return HttpResponse(json.dumps(resp), content_type="application/json")

def data_acquisition(request):
    return render(request, 'article/data_acquitision.html')

article/templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">班级分组</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">班级介绍</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <div class="form-group">
                    <label for="jsonfile">json文件</label>
                    <!-- 上传区域 -->
                    <input type="file" class="form-control" id="jsonfile" name="jsonfile">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

article/templates/article/data_acquitision.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>信息系统规划与建设</title>
    <style media="screen">
        div.div_padding{padding-left:30px; padding-top: 30px;padding-bottom: 10px}
    </style>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">输入</a></li>
            <li role="presentation"><a href="#">分组</a></li>
            <li role="presentation"><a href="#">小组信息</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">Buiding group System</h3>
      </div>

      <div class="jumbotron">
        <h1>分组数据采集</h1>
          <p class="lead">采集说明：各位同学大家好，这是我们组的调查问卷，主要针对大家的基本信息、技术能力、产品能力、测试评估能力进行调查，我们尽会我们所能保护大家的信息，尊重大家的隐私，请大家放心填写~</p>
      </div>
      <div class="">
        <ul id="top_padding_1" class="nav nav-tabs">
    		  <li role="presentation" class="active"><a href="#">信息内容</a></li>
    		</ul>
      <form class="form-horizontal" action="#" method="post">

        <div class="row marketing">

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">1、您的姓名</p>
                  <p><input class="form-control" type="text" name="name" placeholder="李某某"></p>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">2、您的性别</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_2" id="inlineRadio1" value="1"> 男
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_2" id="inlineRadio2" value="0"> 女
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">3、本科是否在北大</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_3" id="inlineRadio1" value="1"> 是
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_3" id="inlineRadio2" value="0"> 否
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">4、参与开发的信息系统项目个数（参与写代码的工作）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_4" id="inlineRadio1" value="1"> 0
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_4" id="inlineRadio2" value="3"> 1~2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_4" id="inlineRadio3" value="5"> 3个及以上
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">5、您写过的代码行数</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_5" id="inlineRadio1" value="1"> 0~3000
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_5" id="inlineRadio2" value="3"> 3000~10000
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_5" id="inlineRadio3" value="5"> 10000以上
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">6、您给您的编程能力打分（最高分5分）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_6" id="inlineRadio1" value="1"> 1
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_6" id="inlineRadio2" value="2"> 2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_6" id="inlineRadio3" value="3"> 3
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_6" id="inlineRadio4" value="4"> 4
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_6" id="inlineRadio5" value="5"> 5
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-12">
                  <p id="top_line">7、您参与的相关产品经历的个数（上过相关课程，有相关实习、在项目中担任过相关角色都算）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_7" id="inlineRadio1" value="1"> 1
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_7" id="inlineRadio2" value="2"> 2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_7" id="inlineRadio3" value="3"> 3
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_7" id="inlineRadio4" value="4"> 4
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_7" id="inlineRadio5" value="5"> 5
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-12">
                  <p id="top_line">8、您会使用的原型设计工具个数（如Mockplus、Axure Pro、Justinmind、Invision等）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_8" id="inlineRadio1" value="1"> 0
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_8" id="inlineRadio2" value="3"> 1~2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_8" id="inlineRadio3" value="5"> 3个及以上
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-12">
                  <p id="top_line">9、请给您的组织协调能力打分（最高5分）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_9" id="inlineRadio1" value="1"> 1
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_9" id="inlineRadio2" value="2"> 2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_9" id="inlineRadio3" value="3"> 3
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_9" id="inlineRadio4" value="4"> 4
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_9" id="inlineRadio5" value="5"> 5
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-6">
                  <p id="top_line">10、您有过系统测试评估的经历吗？</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_10" id="inlineRadio1" value="1"> 有
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_10" id="inlineRadio2" value="0"> 没有
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-12">
                  <p id="top_line">11、您掌握几种系统评估方法（如德尔菲法、投入产出模型、接受度模型、成功模型、成熟度模型、净现值法、NPV法、成本效益分析、决策分析等等...）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_11" id="inlineRadio1" value="1"> 0
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_11" id="inlineRadio2" value="3"> 1~2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_11" id="inlineRadio3" value="5"> 3个及以上
                  </label>
              </div>
          </div>

          <div class="row form-group div_padding">
              <div class="col-md-12">
                  <p id="top_line">12、您认为您的系统评估能力怎么样（最高5分）</p>
                  <label class="radio-inline">
                    <input type="radio" name="question_12" id="inlineRadio1" value="1"> 1
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_12" id="inlineRadio2" value="2"> 2
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_12" id="inlineRadio3" value="3"> 3
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_12" id="inlineRadio4" value="4"> 4
                  </label>
                  <label class="radio-inline">
                    <input type="radio" name="question_12" id="inlineRadio5" value="5"> 5
                  </label>
              </div>
          </div>

          <p align="center"><a class="btn btn-lg btn-success" href="#" role="button">提交</a></p>
        </div>
      </form>
      </div>

      <footer class="footer">
        <p>&copy; 2018 信息系统设计与规划, 第三组</p>
      </footer>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

article/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}
         · <a href="#" onclick="confirm_delete()">删除分组</a>
         · <a href="{% url "article:article_update" article.id %}">编辑分组</a>
        </div>
        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
            <p>{{ article.jsonfile.name }}</p>
            <br/>
            <ol type="I">
                <li><a href="sum" >json测试</a></li><br/>
                <li><a href="upload/jsons/group_data.json" >查看json数据</a></li><br/>
                <li><a href="file_cluster" >执行分组</a></li><br/>
                <li><a href="article/groups_result.json" >分组结果</a></li>
            </ol>
        </div>
        <img src="C:\Users\Administrator.QH-20150404EHBO\PycharmProjects\firstDjango\blog\best_cluster_result.png"/>
    </div>
</div>


<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>



{% endblock content %}

article/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <!-- 同样改写 href -->
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

article/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">班级分组</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">班级介绍</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}